In [46]:
import pandas as pd
from sklearn.preprocessing import label_binarize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
import plotly.express as px

import warnings
warnings.filterwarnings("ignore")
#Please ignore the warnings with version change

In [47]:
# Insurance Fraud Dataset
trainfile = r"C:\Users\hgaje\Desktop\ASU\Machine Leaning In Business\ML_2\Insurance Fraud - TRAIN-3000.csv"
trainData = pd.read_csv(trainfile) #creates a dataframe
testfile = r"C:\Users\hgaje\Desktop\ASU\Machine Leaning In Business\ML_2\Insurance Fraud -TEST-12900.csv"
testData = pd.read_csv(testfile)  #creates a dataframe


print(trainData.shape)
print(testData.shape)

(2999, 32)
(12918, 32)


In [94]:
trainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MONTH                 2999 non-null   object
 1   WEEKOFMONTH           2999 non-null   object
 2   DAYOFWEEK             2999 non-null   object
 3   MAKE                  2999 non-null   object
 4   ACCIDENTAREA          2999 non-null   object
 5   DAYOFWEEKCLAIMED      2999 non-null   object
 6   MONTHCLAIMED          2999 non-null   object
 7   WEEKOFMONTHCLAIMED    2999 non-null   object
 8   SEX                   2999 non-null   object
 9   MARITALSTATUS         2999 non-null   object
 10  AGE                   2999 non-null   int64 
 11  FAULT                 2999 non-null   object
 12  POLICYTYPE            2999 non-null   object
 13  VEHICLECATEGORY       2999 non-null   object
 14  VEHICLEPRICE          2999 non-null   object
 15  REPNUMBER             2999 non-null   

In [50]:
testData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12918 entries, 0 to 12917
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MONTH                 12918 non-null  object
 1   WEEKOFMONTH           12918 non-null  object
 2   DAYOFWEEK             12918 non-null  object
 3   MAKE                  12918 non-null  object
 4   ACCIDENTAREA          12918 non-null  object
 5   DAYOFWEEKCLAIMED      12918 non-null  object
 6   MONTHCLAIMED          12918 non-null  object
 7   WEEKOFMONTHCLAIMED    12918 non-null  object
 8   SEX                   12918 non-null  object
 9   MARITALSTATUS         12918 non-null  object
 10  AGE                   12918 non-null  int64 
 11  FAULT                 12918 non-null  object
 12  POLICYTYPE            12918 non-null  object
 13  VEHICLECATEGORY       12918 non-null  object
 14  VEHICLEPRICE          12918 non-null  object
 15  REPNUMBER             12918 non-null

In [51]:
trainData.isna().sum() # Data is clean their is no missing values in the given dataset

MONTH                   0
WEEKOFMONTH             0
DAYOFWEEK               0
MAKE                    0
ACCIDENTAREA            0
DAYOFWEEKCLAIMED        0
MONTHCLAIMED            0
WEEKOFMONTHCLAIMED      0
SEX                     0
MARITALSTATUS           0
AGE                     0
FAULT                   0
POLICYTYPE              0
VEHICLECATEGORY         0
VEHICLEPRICE            0
REPNUMBER               0
DEDUCTIBLE              0
DRIVERRATING            0
DAYS_POLICY_ACCIDENT    0
DAYS_POLICY_CLAIM       0
PASTNUMBEROFCLAIMS      0
AGEOFVEHICLE            0
AGEOFPOLICYHOLDER       0
POLICEREPORTFILED       0
WITNESSPRESENT          0
AGENTTYPE               0
NUMBEROFSUPPLIMENTS     0
ADDRESSCHANGE_CLAIM     0
NUMBEROFCARS            0
YEAR                    0
BASEPOLICY              0
FRAUDFOUND              0
dtype: int64

In [52]:
testData.isna().sum()

MONTH                   0
WEEKOFMONTH             0
DAYOFWEEK               0
MAKE                    0
ACCIDENTAREA            0
DAYOFWEEKCLAIMED        0
MONTHCLAIMED            0
WEEKOFMONTHCLAIMED      0
SEX                     0
MARITALSTATUS           0
AGE                     0
FAULT                   0
POLICYTYPE              0
VEHICLECATEGORY         0
VEHICLEPRICE            0
REPNUMBER               0
DEDUCTIBLE              0
DRIVERRATING            0
DAYS_POLICY_ACCIDENT    0
DAYS_POLICY_CLAIM       0
PASTNUMBEROFCLAIMS      0
AGEOFVEHICLE            0
AGEOFPOLICYHOLDER       0
POLICEREPORTFILED       0
WITNESSPRESENT          0
AGENTTYPE               0
NUMBEROFSUPPLIMENTS     0
ADDRESSCHANGE_CLAIM     0
NUMBEROFCARS            0
YEAR                    0
BASEPOLICY              0
FRAUDFOUND              0
dtype: int64

In [53]:
trainData.describe()

AGE    REPNUMBER   DEDUCTIBLE         YEAR
count  2999.000000  2999.000000  2999.000000  2999.000000
mean     40.055352     8.511837   407.302434  1995.114038
std      13.497026     4.601437    41.847258     0.606007
min       0.000000     1.000000   300.000000  1994.000000
25%      31.000000     4.000000   400.000000  1995.000000
50%      38.000000     9.000000   400.000000  1995.000000
75%      49.000000    12.000000   400.000000  1995.000000
max      80.000000    16.000000   700.000000  1996.000000

In [54]:
#To get list of names of all Columns from a dataframe

TrainCols = list(trainData.columns.values)
TestCols = list(testData.columns.values)
print(TrainCols)
print(TestCols)

['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'FRAUDFOUND']
['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'F

In [55]:
# Seperate Target column from Train Data
Xtrain = trainData[TrainCols[0:len(TrainCols)-1]].copy()
Ytrain = trainData[['FRAUDFOUND']].copy()
print("Train Set shape:")
print(Xtrain.shape)
print(Ytrain.shape)
Xtest = testData[TestCols[0:len(TestCols)-1]].copy()
Ytest = testData[['FRAUDFOUND']].copy()
print("Test Set shape:")
print(Xtest.shape)
print(Ytest.shape)

Train Set shape:
(2999, 31)
(2999, 1)
Test Set shape:
(12918, 31)
(12918, 1)


In [56]:
#List of Categorical Features
categoricalFeatures = ['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'BASEPOLICY']


In [57]:
# OneHotEncoding on Train (fit & transform)
# OneHotEncoding is to be done on Categorical variables.
ohe = OneHotEncoder(handle_unknown='ignore', sparse=False)

# Fit and transform the categorical features
Xcat = ohe.fit_transform(Xtrain[categoricalFeatures])

# Get the feature names after one-hot encoding
feature_names = ohe.get_feature_names_out(input_features=categoricalFeatures)

# Create a DataFrame with the one-hot encoded features
Xcat = pd.DataFrame(Xcat, columns=feature_names, index=Xtrain.index)

# Concatenate the one-hot encoded features to the original dataframe
Xtrain = pd.concat([Xtrain, Xcat], axis=1)

# Drop the original categorical features
Xtrain.drop(labels=categoricalFeatures, axis=1, inplace=True)

# Sample 5 rows to check the result
Xtrain.sample(5)

AGE  REPNUMBER  DEDUCTIBLE  YEAR  MONTH_Apr  MONTH_Aug  MONTH_Dec  \
151    62          8         400  1994        0.0        1.0        0.0   
1670   34          2         400  1995        0.0        0.0        0.0   
1266   26          8         400  1995        1.0        0.0        0.0   
2181   51         13         400  1996        0.0        0.0        0.0   
1045   61          3         400  1994        0.0        0.0        0.0   

      MONTH_Feb  MONTH_Jan  MONTH_Jul  ...  ADDRESSCHANGE_CLAIM_4_to_8_years  \
151         0.0        0.0        0.0  ...                               0.0   
1670        1.0        0.0        0.0  ...                               0.0   
1266        0.0        0.0        0.0  ...                               0.0   
2181        0.0        0.0        1.0  ...                               0.0   
1045        0.0        0.0        1.0  ...                               0.0   

      ADDRESSCHANGE_CLAIM_no_change  ADDRESSCHANGE_CLAIM_under_6_months  \
151                             0.0                                 0.0   
1670                            1.0                                 0.0   
1266                            1.0                                 0.0   
2181                            1.0                                 0.0   
1045                            1.0                                 0.0   

      NUMBEROFCARS_1-vehicle  NUMBEROFCARS_2-vehicles  NUMBEROFCARS_3_to_4  \
151                      1.0                      0.0                  0.0   
1670                     1.0                      0.0                  0.0   
1266                     1.0                      0.0                  0.0   
2181                     1.0                      0.0                  0.0   
1045                     1.0                      0.0                  0.0   

      NUMBEROFCARS_5_to_8  BASEPOLICY_All_Perils  BASEPOLICY_Collision  \
151                   0.0                    1.0                   0.0   
1670                  0.0                    0.0                   1.0   
1266                  0.0                    0.0                   1.0   
2181                  0.0                    0.0                   1.0   
1045                  0.0                    1.0                   0.0   

      BASEPOLICY_Liability  
151                    0.0  
1670                   0.0  
1266                   0.0  
2181                   0.0  
1045                   0.0  

[5 rows x 150 columns]

In [59]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(Xtest[categoricalFeatures]),columns=ohe.get_feature_names_out(),index=Xtest.index)
Xtest = pd.concat([Xtest,Xcat],axis=1)
Xtest.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtest.sample(5)

AGE  REPNUMBER  DEDUCTIBLE  YEAR  MONTH_Apr  MONTH_Aug  MONTH_Dec  \
6169    39          4         400  1994        0.0        0.0        0.0   
7131    29         12         400  1996        0.0        0.0        0.0   
10618   45         16         400  1995        1.0        0.0        0.0   
2480    46         12         400  1995        0.0        0.0        0.0   
9270    42         16         400  1996        0.0        0.0        0.0   

       MONTH_Feb  MONTH_Jan  MONTH_Jul  ...  ADDRESSCHANGE_CLAIM_4_to_8_years  \
6169         0.0        0.0        0.0  ...                               0.0   
7131         0.0        0.0        0.0  ...                               0.0   
10618        0.0        0.0        0.0  ...                               0.0   
2480         0.0        0.0        0.0  ...                               0.0   
9270         0.0        1.0        0.0  ...                               0.0   

       ADDRESSCHANGE_CLAIM_no_change  ADDRESSCHANGE_CLAIM_under_6_months  \
6169                             1.0                                 0.0   
7131                             1.0                                 0.0   
10618                            1.0                                 0.0   
2480                             1.0                                 0.0   
9270                             1.0                                 0.0   

       NUMBEROFCARS_1-vehicle  NUMBEROFCARS_2-vehicles  NUMBEROFCARS_3_to_4  \
6169                      1.0                      0.0                  0.0   
7131                      1.0                      0.0                  0.0   
10618                     1.0                      0.0                  0.0   
2480                      1.0                      0.0                  0.0   
9270                      1.0                      0.0                  0.0   

       NUMBEROFCARS_5_to_8  BASEPOLICY_All_Perils  BASEPOLICY_Collision  \
6169                   0.0                    1.0                   0.0   
7131                   0.0                    0.0                   1.0   
10618                  0.0                    1.0                   0.0   
2480                   0.0                    0.0                   0.0   
9270                   0.0                    1.0                   0.0   

       BASEPOLICY_Liability  
6169                    0.0  
7131                    0.0  
10618                   0.0  
2480                    1.0  
9270                    0.0  

[5 rows x 150 columns]

In [62]:
print(Xtrain.shape)
print(Xtest.shape)

(2999, 150)
(12918, 150)


In [63]:
dt = DecisionTreeClassifier()
dt.fit(Xtrain, Ytrain)

DecisionTreeClassifier()

In [64]:
rf = RandomForestClassifier()
rf.fit(Xtrain, Ytrain)

RandomForestClassifier()

In [67]:
X_Pred = dt.predict(Xtest)
XPred = dt.predict(Xtrain)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred))
print("Max Depth",dt.get_depth())
print("Leaf",dt.get_n_leaves())
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred))


Train Accuracy: 1.0
Test Accuracy: 0.880631676730144
Confusion Matrix for Decision Tree:
[[10931  1489]
 [   53   445]]
Max Depth 24
Leaf 285
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       1.00      0.88      0.93     12420
         Yes       0.23      0.89      0.37       498

    accuracy                           0.88     12918
   macro avg       0.61      0.89      0.65     12918
weighted avg       0.97      0.88      0.91     12918



In [68]:
X_Pred1 = rf.predict(Xtest)
XPred1 = rf.predict(Xtrain)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred1))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred1))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred1))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred1))

Train Accuracy: 1.0
Test Accuracy: 0.9633844248335656
Confusion Matrix for Decision Tree:
[[12025   395]
 [   78   420]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.99      0.97      0.98     12420
         Yes       0.52      0.84      0.64       498

    accuracy                           0.96     12918
   macro avg       0.75      0.91      0.81     12918
weighted avg       0.98      0.96      0.97     12918



In [95]:
#Hyperparameter tuning done for decision tree classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,300,10),'max_depth': 
            range(5,30,2),'criterion':['gini','entropy', 'gain']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=100,cv=5)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)

# all_inter = dt_random.cv_results_
# print(all_inter)

print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("time taken to complete %s seconds" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 30, 'max_depth': 25, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.907029
time taken to complete 13.282195568084717 seconds


In [91]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree")
dt_grid = GridSearchCV(dt,parameters)
dt_grid.fit(Xtrain, Ytrain)

# Access the number of iterations performed
n_iterations = len(dt_grid.cv_results_['params'])

print(f"Number of iterations performed: {n_iterations}")

grid_parm1=dt_grid.best_params_
grid = dt_grid.best_estimator_
best_score = dt_grid.best_score_ # This line of code will return the accuracy of the best model optimzied by decision tree classifier
print(best_score)
print(grid)
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("Time taken to complete %s seconds" % (time.time() - start_time))

GridSearchCV-Decision tree
Number of iterations performed: 754
0.8876288258208124
DecisionTreeClassifier(criterion='entropy', max_depth=7, min_samples_leaf=30)
{'criterion': 'entropy', 'max_depth': 7, 'min_samples_leaf': 30}
accuracy Score for Decision Tree:0.907029
Time taken to complete 111.36008977890015 seconds


In [87]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier 
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(Xtrain,Ytrain)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(Xtrain,Ytrain)
dtGrid_predict = dtGrid.predict(Xtest)

In [88]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.9070289518501315
Confusion Matrix for Decision Tree:
[[11568   852]
 [  349   149]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.93      0.95     12420
         Yes       0.15      0.30      0.20       498

    accuracy                           0.91     12918
   macro avg       0.56      0.62      0.57     12918
weighted avg       0.94      0.91      0.92     12918

[0.74615385 0.69807692 0.54375    0.50240385 0.56962025]


In [73]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')

Test Accuracy: 0.9070289518501315
Confusion Matrix for Decision Tree:
[[11568   852]
 [  349   149]]
Printing the precision and recall, among other metrics


In [74]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth': 
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(Xtrain, Ytrain)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest
{'n_estimators': 30, 'min_samples_leaf': 10, 'max_features': 30, 'max_depth': 7}
accuracy Score for Decision Tree:0.926769
--- 12.502989768981934 seconds ---
